version: '3.4'
services:
  spring-security-ms-db:
    image: postgres
    ports:
      - "9009:5432"
    volumes:
      - db_data_spring_security-management:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: springsecurity
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres-spring-security
  kafka-1:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1 #broker id
      - KAFKA_KRAFT_CLUSTER_ID=DyZFl62GQIKXyo3ZPSKF5Q #Cluster id
      - KAFKA_CFG_PROCESS_ROLES_ID=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://[::1]:9090,CONTROLLER://9001,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9090,EXTERNAL://:host.docker.internal:9092
      - KAFKA_CFG_LISTENERS_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAMES=PLAINTEXT
    volumes:
      - /Users/kafka/docker-compose/volumes/server-1:/bitnami/kafka
volumes:
  db_data_spring_security-management: {}
