server:
  port: 8084
spring:
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer  # Serializer for Long key
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all                # Wait for all replicas to acknowledge
      retries: 3               # Number of retries in case of a failure
      batch-size: 16384        # Batch size for sending messages
      linger-ms: 1             # Delay in milliseconds to send messages in batches
      buffer-memory: 33554432  # Buffer size for storing unsent records

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  security:
    jwt-secret-key: eW91ci0yNTYtYml0LXNlY3JldHlvdXItMjU2LWJpdC1zZWNyZXR5b3VyLTI1Ni1iaXQtc2VjcmV0eW91ci0yNTYtYml0LXNlY3JldHlvdXItMjU2LWJpdC1zZWNyZXR5b3VyLTI1Ni1iaXQtc2VjcmV0
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:9009/postgres-spring-security
    password: ${POSTGRES_PASSWORD:123456}
    username: ${POSTGRES_USER:springsecurity}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: springsecurity

  config:
    import: application_prod.yaml
  profiles:
    active: default